/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrerascoches;

import java.awt.EventQueue;
import java.awt.TextField;

import javax.swing.JFrame;
import javax.swing.JProgressBar;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;


/**
 *
 * @author Alumno Tarde
 */
public class Carrera extends javax.swing.JFrame {

    /**
     * Creates new form Carrera
     */
    public Carrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pbCoche1 = new javax.swing.JProgressBar();
        pbCoche2 = new javax.swing.JProgressBar();
        lblNewLabel = new javax.swing.JLabel();
        lblNewLabel_1 = new javax.swing.JLabel();
        pbCoche3 = new javax.swing.JProgressBar();
        lblNewLabel_2 = new javax.swing.JLabel();
        tfDistancia = new java.awt.TextField();
        btCorrer = new javax.swing.JButton();
        lblDistancia = new javax.swing.JLabel();
        lbMarcador = new javax.swing.JLabel();
        progresoCoche1 = new javax.swing.JLabel();
        pbCoche4 = new javax.swing.JProgressBar();
        lblNewLabel_3 = new javax.swing.JLabel();
        pbCoche5 = new javax.swing.JProgressBar();
        lblNewLabel_4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jFrame1"); // NOI18N

        lblNewLabel.setText("Coche 1");

        lblNewLabel_1.setText("Coche 2");

        lblNewLabel_2.setText("Coche 3");

        tfDistancia.setText("textField1");
        tfDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDistanciaActionPerformed(evt);
            }
        });

        btCorrer.setText("Correr");
        btCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCorrerActionPerformed(evt);
            }
        });

        lblDistancia.setText("Distancia");

        lbMarcador.setText("Marcador");

        progresoCoche1.setText("Prog Coche");

        lblNewLabel_3.setText("Coche 2");

        lblNewLabel_4.setText("Coche 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewLabel_3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pbCoche4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewLabel_4)
                            .addComponent(pbCoche5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNewLabel_1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pbCoche2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pbCoche1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewLabel_2)
                                    .addComponent(pbCoche3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btCorrer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(progresoCoche1)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDistancia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbMarcador))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btCorrer)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewLabel)
                            .addComponent(progresoCoche1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDistancia))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbCoche1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarcador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewLabel_1)
                .addGap(18, 18, 18)
                .addComponent(pbCoche2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewLabel_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbCoche3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewLabel_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbCoche4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewLabel_4)
                .addGap(12, 12, 12)
                .addComponent(pbCoche5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDistanciaActionPerformed

    private void btCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCorrerActionPerformed
    correr();
    }//GEN-LAST:event_btCorrerActionPerformed

    /**
     * @param args
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCorrer;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lbMarcador;
    private javax.swing.JLabel lblDistancia;
    private javax.swing.JLabel lblNewLabel;
    private javax.swing.JLabel lblNewLabel_1;
    private javax.swing.JLabel lblNewLabel_2;
    private javax.swing.JLabel lblNewLabel_3;
    private javax.swing.JLabel lblNewLabel_4;
    private javax.swing.JProgressBar pbCoche1;
    private javax.swing.JProgressBar pbCoche2;
    private javax.swing.JProgressBar pbCoche3;
    private javax.swing.JProgressBar pbCoche4;
    private javax.swing.JProgressBar pbCoche5;
    private javax.swing.JLabel progresoCoche1;
    private java.awt.TextField tfDistancia;
    // End of variables declaration//GEN-END:variables

	private void correr() {
		
		int distancia = 
			Integer.parseInt(tfDistancia.getText());
		
		final Coches coche1 = new Coches(5, distancia, lbMarcador, "Opel");
		final Coches coche2 = new Coches(20, distancia, lbMarcador, "Ford");
		final Coches coche3 = new Coches(30, distancia, lbMarcador, "Seat");
		
		coche1.addPropertyChangeListener(new PropertyChangeListener() {
			@Override
			public void propertyChange(PropertyChangeEvent event) {
				if (event.getPropertyName().equals("progress")) {
					pbCoche1.setValue((Integer) event.getNewValue());
					progresoCoche1.setText(
						event.getNewValue() + " %");
				}
				if (event.getPropertyName().equals("ganador")) {
					coche2.cancel(true);
					coche3.cancel(true);
				}
			}
		});
		coche2.addPropertyChangeListener(new PropertyChangeListener() {
			@Override
			public void propertyChange(PropertyChangeEvent event) {
				if (event.getPropertyName().equals("progress")) {
					pbCoche2.setValue((Integer) event.getNewValue());
				}
				if (event.getPropertyName().equals("ganador")) {
					coche1.cancel(true);
					coche3.cancel(true);
				}
			}
		});
		coche3.addPropertyChangeListener(new PropertyChangeListener() {
			@Override
			public void propertyChange(PropertyChangeEvent event) {
				if (event.getPropertyName().equals("progress")) {
					pbCoche3.setValue((Integer) event.getNewValue());
				}
				if (event.getPropertyName().equals("ganador")) {
					coche1.cancel(true);
					coche2.cancel(true);
				}
			}
		});
		
		coche1.execute();
		coche2.execute();
		coche3.execute();
	}

	private void initialize() {
		jFrame1 = new JFrame();
		jFrame1.setTitle("Carrera");
		jFrame1.setBounds(100, 100, 450, 300);
		jFrame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		jFrame1.getContentPane().setLayout(null);
		jFrame1.getContentPane().add(getPbCoche1());
		jFrame1.getContentPane().add(getPbCoche2());
		jFrame1.getContentPane().add(getLblNewLabel());
		jFrame1.getContentPane().add(getLblNewLabel_1());
		jFrame1.getContentPane().add(getPbCoche3());
		jFrame1.getContentPane().add(getLblNewLabel_2());
		jFrame1.getContentPane().add(getTfDistancia());
		jFrame1.getContentPane().add(getBtCorrer());
		jFrame1.getContentPane().add(getLblDistancia());
		jFrame1.getContentPane().add(getLbMarcador());
		jFrame1.getContentPane().add(getProgresoCoche1());
	}
	public JProgressBar getPbCoche1() {
		if (pbCoche1 == null) {
			pbCoche1 = new JProgressBar();
			pbCoche1.setBounds(10, 65, 422, 19);
		}
		return pbCoche1;
	}
	public JProgressBar getPbCoche2() {
		if (pbCoche2 == null) {
			pbCoche2 = new JProgressBar();
			pbCoche2.setBounds(10, 137, 422, 19);
		}
		return pbCoche2;
	}
	public JLabel getLblNewLabel() {
		if (lblNewLabel == null) {
			lblNewLabel = new JLabel("Coche 1");
			lblNewLabel.setBounds(10, 43, 46, 14);
		}
		return lblNewLabel;
	}
	public JLabel getLblNewLabel_1() {
		if (lblNewLabel_1 == null) {
			lblNewLabel_1 = new JLabel("Coche 2");
			lblNewLabel_1.setBounds(10, 114, 46, 14);
		}
		return lblNewLabel_1;
	}
	public JProgressBar getPbCoche3() {
		if (pbCoche3 == null) {
			pbCoche3 = new JProgressBar();
			pbCoche3.setString("34");
			pbCoche3.setBounds(10, 207, 422, 19);
		}
		return pbCoche3;
	}
	public JLabel getLblNewLabel_2() {
		if (lblNewLabel_2 == null) {
			lblNewLabel_2 = new JLabel("Coche 3");
			lblNewLabel_2.setBounds(10, 182, 46, 14);
		}
		return lblNewLabel_2;
	}
	public TextField getTfDistancia() {
		if (tfDistancia == null) {
			tfDistancia = new TextField();
			tfDistancia.setBounds(247, 12, 86, 20);
			tfDistancia.setColumns(10);
		}
		return tfDistancia;
	}
	public JButton getBtCorrer() {
		if (btCorrer == null) {
			btCorrer = new JButton("Correr");
			btCorrer.addActionListener(new ActionListener() {
                                @Override
				public void actionPerformed(ActionEvent arg0) {
					correr();
				}
			});
			btCorrer.setBounds(343, 11, 89, 23);
		}
		return btCorrer;
	}
	public JLabel getLblDistancia() {
		if (lblDistancia == null) {
			lblDistancia = new JLabel("Distancia");
			lblDistancia.setBounds(176, 15, 72, 14);
		}
		return lblDistancia;
	}
	public JLabel getLbMarcador() {
		if (lbMarcador == null) {
			lbMarcador = new JLabel("");
			lbMarcador.setBounds(147, 241, 144, 14);
		}
		return lbMarcador;
	}
	public JLabel getProgresoCoche1() {
		if (progresoCoche1 == null) {
			progresoCoche1 = new JLabel("");
			progresoCoche1.setBounds(65, 40, 46, 14);
		}
		return progresoCoche1;
	}
}